###############################################################################
#    choose an output folder (reference folder will be created inside)        #
###############################################################################
output_folder: splicewiz_output

# choose number of cores to use in analysis
cores: 32

###############################################################################
#                       build reference variables                             #
###############################################################################
genome_fasta: /home/charlie/projects/genomes/dm_bdgp632.fa
genome_gtf: /home/charlie/projects/genomes/dm_bdgp632_with_copia.gtf

genomeSAindexNbases: 12 # default 14 is too high for drosophila genome size
ontology_species: Drosophila melanogaster

###############################################################################
#                  alignment and analysis variables                           #
###############################################################################
fastq_folder_path: /home/charlie/projects/fastqs/C380_CNS
fastq_suffix: .fq.gz # e.g. .fq or .fq.gz
is_paired: TRUE # TRUE or FALSE

###############################################################################
#       visualization parameters to be set after examining the res_edgeR      #
###############################################################################

gene: copia_BDGP6.32_30
row: 3957

