###############################################################################
#    choose an output folder (reference folder will be created inside)        #
###############################################################################
output_folder: splicewiz_output

# choose number of cores to use in analysis
cores: 30

###############################################################################
#                       build reference variables                             #
###############################################################################
genome_fasta: genomes/dm_bdgp632_3L_only.fa
genome_gtf: genomes/dm_bdgp632_with_copia.gtf

genomeSAindexNbases: 12 # default 14 is too high for drosophila genome size
ontology_species: Drosophila melanogaster

###############################################################################
#                  alignment and analysis variables                           #
###############################################################################
# fastq files from the experiment should be at the top level of the defined path
fastq_folder_path: fastqs/C380_CNS
fastq_suffix: .fq.gz # e.g. .fq or .fq.gz
is_paired: TRUE # TRUE or FALSE

###############################################################################
#       visualization parameters to be set after examining the res_edgeR      #
###############################################################################

gene: copia_BDGP6.32_30
row: 3957

